wandb_version: 1

optimizer:
  desc: null
  value: SGD
learning_rate:
  desc: null
  value: 0.001
momentum:
  desc: null
  value: 0.9
input_size:
  desc: null
  value:
  - 800
  - 1333
architecture:
  desc: null
  value: resnet34
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711682862.038586
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.18
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
